New Advanced Configuration Options
senaite/senaite.sync pull request #42
Opened 2018-05-04 10:31 UTC by nihadness

## Current behavior before PR

1. 'Adding a new Remote From' and 'Data of existing Remotes' are in the same View.
2. It is not possible to specify object types which a user doesn't want to import.
3. While importing from different remotes, objects with the same ID are _overriden_ or not being updated.

## Desired behavior after PR is merged

1. The old (`/sync`) view will only list the Fetched Data and their Actions. New (`/sync_add`) View will be available to add a new remote.
2. A new  field will be added to 'Add' form where users can define Content Types- separated by comma, to be skipped during import.
3. New 'Prefix Logic' will be introduced and users will be able to define a prefix for each remote and use them for specific content types. It will help the system to save _similar_ objects from different Remotes separately. Prefixes will be added only to object ID's so far... If Prefix is empty, it will behave in the old, standard way.

-----
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2018-05-09 10:57 UTC, juangallostra approved these changes

2018-05-10 08:53 UTC, xispa requested changes

2018-05-10 08:53 UTC, xispa commented on src/senaite/sync/browser/add.py
> +                url = "http://{}".format(url)
Make "http**s**" as default's

2018-05-10 08:53 UTC, xispa commented on src/senaite/sync/browser/add.py
> +            import_settings = True if form.get("import_settings") == 'on' else False
Please, replace it as follows:
```python
import_settings = form.get('import_settings') == 'on'
```

2018-05-10 08:53 UTC, xispa commented on src/senaite/sync/browser/add.py
> +                                                unwanted_content_types)
I suggest to reduce a bit the complexity by adding a function to get the content types:
```python
def get_content_types(self, content_types):
    if not content_types:
        return list()
    portal_types = api.get_tool("portal_types")
    ...
    return content_types
```
So, you'll only need to do the following here:
```python
prefixable_types = self.get_content_types(form.get("prefixable_types", None))
content_types = self.get_content_types(form.get("content_types", None))
unwanted_content_types = self.get_content_types(format.get("unwanted_content_types", None))
```
Note with this change you'll be able to remove the logic for `prefixable_types` below.

2018-05-10 08:53 UTC, xispa commented on src/senaite/sync/browser/templates/add.pt
> +               value="Save & Fetch"/>
Better "Save and fetch"

2018-05-10 08:53 UTC, xispa commented on src/senaite/sync/browser/templates/sync.pt
> +                  Users will <span tal:condition="python: not view.storage[storage]['configuration'].get('import_users')">NOT</span> be imported.<br><br>
Would be nice to create a function (something like `def get_storage_setting(self, parameter, section='configuration')` in the view to make the retrieval of all these settings easier. A thumb of rule is to always try to keep the tpl as much simpler as possible, with less logic as possible.

2018-05-10 08:53 UTC, xispa commented on src/senaite/sync/browser/views.py
> +            prefixable_types = storage["configuration"].get("prefixable_types", [])
Same function suggested above to be called from the tpl, could be used here to get all these settings in an easier way

2018-05-10 08:53 UTC, xispa commented on src/senaite/sync/browser/views.py
> +            prefixable_types = storage["configuration"].get("prefixable_types", [])
ditto

2018-05-10 08:53 UTC, xispa commented on src/senaite/sync/importstep.py
> +                    self.sh.update_by_remote_path(p_path, local_uid=p_local_uid)
Please, add some comments here to make the code more understandable for newbies

2018-05-10 09:19 UTC, nihadness commented on src/senaite/sync/browser/add.py
> +                url = "http://{}".format(url)
Safety first! : )

2018-05-10 10:26 UTC, xispa commented on src/senaite/sync/utils.py
> +    ret = filter(lambda ct, types=portal_types: ct in types, ret)
Just ensure there are no duplicates
```python
ret = list(set(ret))
```

2018-05-10 11:33 UTC, xispa approved these changes

2018-05-10 11:33 UTC, merged